### ISSUE TITLE
Live reload not working with imported css files (included via link)

### ISSUE THREAD

**Issue by rizkysyazuli** [mockko/livereload#32]
i have a few css files linked to the master stylesheet via @import method. after a few editing i realized the live reload doesn't run. the page does get refreshed by the extension, but without the live reload thing.. i hope you understand what i mean :P

i'm working with SASS files and developing on Safari 5.0.2 (OSX 10.6.4)

**Comment by NV** [comment]
LiveReload currently does not support `@import`. CSSOM provides [CSSImportRule#href](http://dev.w3.org/csswg/cssom/#css-import-rule), so I think I can fix it.

**Comment by rizkysyazuli** [comment]
awesome.. looking forward for the next release :)

**Comment by NV** [comment]
I was not completely accurate. LiveReload supports @import in CSS files, it does not support @import in `<style>`.

index.html

<pre>&lt;link rel="stylesheet" href="main.css"></pre>


main.css

<pre>@import "slave.css";
html {background: red}</pre>


slave.css

<pre>body {background: green}</pre>


When you change slave.css changes should be applied. Everything should work well.

However, this one won't work:

index.html

<pre>&lt;style>@import "slave.css";&lt;style></pre>


I don't see any reason to put `@import` into `<style>`, so I won't fix it.

**Comment by andreyvit** [comment]
LiveReload does not support @import in a sense that it will do a full page reload when slave.css is changed in your example, since it uses `document.getElementsByTagName("link")` to find stylesheets.

Any good ideas on how to handle @import's, aside from doing XMLHTTPRequest on every stylesheet and running a regexp?

**Comment by NV** [comment]
http://github.com/NV/livereload/commit/f185861d59e7b4881785149d3acdf3165d7def22 No XHRs, no regexps. Try it.
1. Open `test/index.html`
2. Change `test/slave.css`

LR will try to reload `test/main.css`. It'll work well. However, `test/slave.css` won't be reloaded because it's cached. I can't bust the cache, because I can't append `?livereload=` to imported stylesheet.

**Comment by NV** [comment]
I've got something working http://github.com/NV/livereload/commit/1ba2a52f174d54e1bd06f52b8cd2d3c6b10323e6

**Comment by andreyvit** [comment]
Wow! NV, you're awesome. I guess we should bake a new version on weekend.

**Comment by rizkysyazuli** [comment]
hell yea!

**Comment by NV** [comment]
> LiveReload does not support @import in a sense that it will do a full page reload when slave.css is changed in your example ...

Instead of full page reload we could reload all stylesheets. http://github.com/NV/livereload/commit/0b4d1fd79ca7708ccaf5454160a834e50da96af1

Reload _just_ imported stylesheet is a bit more complicated. I'll do it later.

**Comment by NV** [comment]
Support for CSS files included with @import.
Closed by c65e295772bf91292c52253a3e3de0f344c1a7f1, #35.
