### ISSUE TITLE
preventing reload when an unrelated css file is changed

### ISSUE THREAD

**Issue by naltatis** [mockko/livereload#47]
At the moment there is a global fallback to reloading the whole page if a file is changed that has nothing to do with the current page:

https://github.com/mockko/livereload/blob/master/src/core.js#L153

What are the thoughts behind that? At least for CSS I can't think of any reason why I want to do this. Could you please make this behavior configurable?
- naltatis

**Comment by NV** [comment]
Yesterday this behavior has been changed. [src/core.js#L137-148](https://github.com/mockko/livereload/blob/c65e295772bf91292c52253a3e3de0f344c1a7f1/src/core.js#L137-148). Instead of reloading the whole page LR just reloads all stylesheets.

The long term plan is to have "strict mode". In "strict mode" LR will do nothing when filename on file-system does not match to the path of css/js/html on the page.

**Comment by naltatis** [comment]
Perfekt!
