### ISSUE TITLE
Problem while using it on windows

### ISSUE THREAD

**Issue by malev** [mockko/livereload#5]
Version:    1.2
Port:       10083
Directory:  C:/cygwin/home/marcos.vanetta/code/newsletter
Extensions: .html .css .js .png .gif .jpg .php .py .rb
LiveReload is waiting for browser to connect.
Browser connected.
C:/InstantRails/ruby/lib/ruby/gems/1.8/gems/eventmachine-0.12.10-x86-mswin32-60/lib/eventmachine.rb:1266: [BUG
] rb_sys_fail(no file watching support on this system) - errno == 0
ruby 1.8.6 (2007-09-24) [i386-mswin32]

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by andreyvit** [comment]
Got ya, will look into this.

**Comment by malev** [comment]
Andreyvit, if you need any help. Please let me know

**Comment by andreyvit** [comment]
I have investigated this. LiveReload won't work on Windows as of now, but we will have a version soon.

Note that you don't need cygwin to install — the correct instructions for Windows are now in README. (But it is no use to you until we rewrite directory watching code.)

**Comment by niksosf** [comment]
I am using 1.9.1 mingw32 with rails 2.3.8 on Windows. I get the problem in issue 1 you now have described in your documentation: chrome disconnects and safari crashes when attempting to connect to the livereload server. Let me know if/how I can help, perhaps trying this and that in case you don't have a Windows box handy.

**Comment by andreyvit** [comment]
Sorry, LiveReload won't work on Windows at the moment (didn't even realize it until I tried myself recently). We'll releasing a Windows-friendly version soon.

**Comment by charlesroper** [comment]
Hi, really excited about this. Ever since XRefresh was essentially abandoned I was getting increasingly anxious that I'd be left without an auto-refresh tool. So THANKYOU guys.

One point regarding the Windows installation instructions: it's probably better to advise people to install the [DevKit](http://rubyinstaller.org/add-ons/devkit/) and then simply run `gem install eventmachine`, rather than specifying the old `--platform=win32` version. Installing DevKit is a bit fiddly at the moment, but it does ensure you get the latest, most stable version of eventmachine compiled for the current line of mingw Rubies for Windows. I'm not sure what the precompiled win32 version of  eventmachine is like, but I know there have been problems in the past.

The RubyInstaller team are working on a DevKit installer to make it super-easy to set up, so things will get easier in that regard. If you've got any questions or need help with the Windows version of Ruby and the DevKit, swing by the [RubyInstaller group](http://groups.google.com/group/rubyinstaller).

**Comment by andreyvit** [comment]
Quite frankly, I'm currently thinking that requiring people to install something like that on Windows at all is close to abuse. We should probably get some kind of one-click installer distribution of Ruby (or something like InstantRails maybe), and pre-package all the needed stuff.

**Comment by andreyvit** [comment]
BTW an update on Windows state: we've got file monitoring working on Windows together with EventMachine in form of a separate gem. Need to transition LiveReload to using it.

Currently it launches a separate subprocess for each monitored folder. If we package something with Ruby 1.9 inside, we should be able to use real threads and get rid of subprocesses.

Unfortunately, I'm real pressed with work at the moment and won't find any time for LiveReload till the weekend for sure.

**Comment by charlesroper** [comment]
Talk to the RubyInstaller guys about creating a package, if that's the route you would like to take - they're experts in such matters.

http://groups.google.com/group/rubyinstaller/topics

I agree that the DevKit is currently quite scary looking to install (although, it's actually very easy), which is why the RubyInstaller team are creating an installer for it.

**Comment by andreyvit** [comment]
Guys, we have directory watching working on Windows now under Ruby 1.8. (For 1.9, I guess Windows API gem has to be rebuilt with a correct version of DLL.) This should mean LiveReload for Windows is coming soon.

**Comment by andreyvit** [comment]
Version 1.4 should work on Windows. Please update and test.
